update usr stack addr, update trap.S from git branch v4-kernel-usrapp-with-syscall-interrupt-in-U-or-S-mode But stil has some err.  The stack need to check.
$./run.sh
....
usr stack 0x80601000
HEAP_START 0x8003a000, HEAP_SIZE 0x5c6000
[kernel] trap_handler Exception(Breakpoint), stval = 0x0, sepc = 0x80020446
[kernel] trap_handler Exception(InstructionPageFault), stval = 0x806000d6, sepc = 0x806000d6
Panicked at src/main.rs:736 Unsupported trap Exception(InstructionPageFault), stval = 0x806000d6, sepc = 0x806000d6

$ rust-objdump -S os >os.s
$ gedit os.s
00000000806000d6 <usr_app_main>:
806000d6: 5d 71        	addi	sp, sp, -80
806000d8: 86 e4        	sd	ra, 72(sp)
806000da: a2 e0        	sd	s0, 64(sp)
806000dc: 80 08        	addi	s0, sp, 80
806000de: 13 05 04 fc  	addi	a0, s0, -64
806000e2: 23 3c a4 fa  	sd	a0, -72(s0)

o symbol table is loaded.  Use the "file" command.
(gdb) print
Display all 200 possibilities? (y or n)
(gdb) print
print         print-object  printf
(gdb) x /10i $pc
=> 0x806000d6 <usr_app_main>:	Cannot access memory at address 0x806000d6
(gdb)