Fix the compiling error. Now compiling is OK!
VirtIOBlock is not mut. But VirtIOBlk's read_block(&mut self,...) will change the
field.

the trait BlockDevice for VirtIOBlock's read_block and write_block will
not mut VirtIOBlock self, including the its field VirtIOBlk.

impl BlockDevice for VirtIOBlock {
    fn read_block(&self, block_id: usize, buf: &mut [u8]) {
        self.0.lock().read_block(block_id, buf).expect("Error when reading VirtIOBlk");
    }
    fn write_block(&self, block_id: usize, buf: &[u8]) {
        self.0.lock().write_block(block_id, buf).expect("Error when writing VirtIOBlk");
    }
}

So the compiler output errs.
===================================

error[E0596]: cannot borrow `self.0` as mutable, as it is behind a `&` reference
   --> src/main.rs:785:9
    |
784 |     fn read_block(&self, block_id: usize, buf: &mut [u8]) {
    |                   ----- help: consider changing this to be a mutable reference: `&mut self`
785 |         self.0.read_block(block_id, buf).expect("Error when reading VirtIOBlk");
    |         ^^^^^^ `self` is a `&` reference, so the data it refers to cannot be borrowed as mutable

error[E0596]: cannot borrow `self.0` as mutable, as it is behind a `&` reference
   --> src/main.rs:788:9
    |
787 |     fn write_block(&self, block_id: usize, buf: &[u8]) {
    |                    ----- help: consider changing this to be a mutable reference: `&mut self`
788 |         self.0.write_block(block_id, buf).expect("Error when writing VirtIOBlk");
    |         ^^^^^^ `self` is a `&` reference, so the data it refers to cannot be borrowed as mutable