fix little bug in rust_main, now fs can work!
drivers::block_device_test() will change the content of virtual disk.
So we need to comment t this function call in rust_main().

Running Result:
[rustsbi] Platform: QEMU
[rustsbi] misa: RV64ACDFIMSU
[rustsbi] mideleg: 0x222
[rustsbi] medeleg: 0xb109
[rustsbi] Kernel entry: 0x80020000
Hello, world begin!
last 1474 Physical Frames.
/**** APPS ****
filea
fileb
**************/
Hello, world end!
Panicked at src/main.rs:39 Shutdown machine!